vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-ivx.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-nand2.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-and2.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-and3.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-or2.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-xor2.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-xnor2.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-fa.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-mux21_generic.vhd
vcom Y:/Microelectronic_Systems/DLX-Project/Files/src/a.b-DataPath.core/a.b-alu.core/a.c.a-basic_blocks/a.c.a.a-rca_generic.vhd